# Generated by Django 4.0.6 on 2022-07-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='id cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id sucursal')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idVendedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='id cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre vendedor')),
                ('run', models.CharField(max_length=15, verbose_name='run')),
                ('cantidadVentas', models.IntegerField(verbose_name='Cantidad de ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='patente')),
                ('marca', models.CharField(max_length=30, verbose_name='marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='modelo')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categoria')),
            ],
        ),
    ]
